# Generated by Django 5.2.7 on 2025-10-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_servicelisting_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicelisting',
            old_name='price',
            new_name='price_cents',
        ),
        migrations.RemoveField(
            model_name='servicelisting',
            name='duration',
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='servicelisting',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
