# Generated by Django 5.2.7 on 2025-10-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_rename_price_servicelisting_price_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
